server:
  port: 80
  
spring:
  datasource:
        url: jdbc:mariadb://localhost:3306/security_default
        username: root
        password: '@Ms38475690'
        driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true #id생성시 자동으로 증가하는 값을 설정 할수 있게 해준다.
    open-in-view: true
      
  main:
    allow-bean-definition-overriding: true
    
  thymeleaf:
    encoding: UTF-8
    template-resolver-order: 1
    #prefix: /WEB-INF/templates
    suffix: .html 
    cache: false
    check-template: false
    reactive:
      max-chunk-size: 1000


